(()=>{'use strict';const $=s=>document.querySelector(s);const menu=$('#menu'),nav=$('#navigation');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Close −':'Menu +'};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu +'});
const items=window.stoneCollection||[];let filtered=items,shown=0,current=0;const grid=$('#archive-grid'),modal=$('#lightbox');
function label(x){return x.category==='inspiration'?'Design inspiration':x.category==='edges'?'Edge profile reference':x.category==='brand'?'Company identity':'Portfolio image'}
function more(){const slice=filtered.slice(shown,shown+16);slice.forEach(x=>{const b=document.createElement('button');b.className='archive-item'+(['edges','brand'].includes(x.category)?' reference':'');b.dataset.photo=x.id;b.setAttribute('aria-label','Open '+label(x)+' '+x.id);const im=document.createElement('img');im.src=x.thumb||x.file;im.alt=x.alt||label(x)+' from the original Arizona Granite and Stone website';im.loading='lazy';im.width=600;im.height=450;const span=document.createElement('span');span.textContent=label(x)+' / '+String(x.id).padStart(3,'0')+' ↗';b.append(im,span);b.onclick=()=>open(x.id);grid.append(b)});shown+=slice.length;$('#load-more').hidden=shown>=filtered.length;$('#shown-count').textContent=shown+' of '+filtered.length+' images';}
function filter(cat){filtered=items.filter(x=>cat==='all'||x.category===cat);shown=0;grid.replaceChildren();$('#gallery-count').textContent=filtered.length+' IMAGES';$('#gallery-note').textContent=cat==='inspiration'?'Inspiration imagery carried over from the original website; these images are not presented as completed company projects.':cat==='edges'?'Edge profile references from the original site. Confirm available profiles and suitability with the team.':'Project photography, edge references and inspiration imagery from the original website.';more()}
function draw(){const x=items[current];$('#viewer-image').src=x.file;$('#viewer-image').alt=x.alt||label(x)+' from Arizona Granite and Stone’s original website';$('#image-label').textContent=label(x)+' · '+(current+1)+' / '+items.length;$('#full-image').href=x.file}
function open(id){const n=items.findIndex(x=>x.id===Number(id));if(n<0)return;current=n;draw();modal.showModal();document.body.style.overflow='hidden'}
$('#close-viewer').onclick=()=>modal.close();modal.addEventListener('close',()=>{document.body.style.overflow=''});modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});function step(n){current=(current+n+items.length)%items.length;draw()}$('#prev-image').onclick=()=>step(-1);$('#next-image').onclick=()=>step(1);modal.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1)}if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}});document.querySelectorAll('.featured[data-photo]').forEach(b=>b.onclick=()=>open(b.dataset.photo));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter(b.dataset.filter)});$('#load-more').onclick=more;filter('all');
document.querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>{document.querySelector('[data-surface="'+b.dataset.choose+'"]').click();$('#planner').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){document.documentElement.classList.add('js-motion');const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.featured,.introduction>div,.steps article').forEach(e=>{e.classList.add('reveal');obs.observe(e)});let ticking=false;const hero=$('.hero-photo'),im=hero.querySelector('img');function render(){ticking=false;const rect=hero.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight){const p=Math.max(-1,Math.min(1,(innerHeight/2-rect.top-rect.height/2)/innerHeight));im.style.transform='translateY('+p*24+'px) scale(1.08)'}}addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(render)}},{passive:true});render()}
})();
