(()=>{'use strict';
let room='Kitchen countertops',surface='Granite';const $=s=>document.querySelector(s),form=$('#inquiry');
const guidance={Granite:'Natural variation makes your actual slab selection an important part of the design.',Quartz:'Explore an engineered surface with no routine sealing. Protect it from direct heat.',Marble:'A natural statement with a lived-in patina. Discuss etching, sealing and care before choosing.','Help me choose':'Bring your inspiration and everyday priorities. The team can help narrow the options.'};
function update(){ $('#brief-room').textContent=room;$('#brief-material').textContent=surface+' · '+$('#readiness').value;$('#brief-guidance').textContent=room==='Outdoor barbecue'&&surface==='Quartz'?'Most quartz is intended for interiors. Ask about outdoor-approved alternatives before selecting a surface.':guidance[surface];$('.sample-slab').dataset.sample=surface;}
function choices(attr,fn){document.querySelectorAll('['+attr+']').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('['+attr+']').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));fn(b.getAttribute(attr));update()}))}
choices('data-room',v=>room=v);choices('data-surface',v=>surface=v);$('#readiness').addEventListener('change',update);
$('#use-brief').addEventListener('click',()=>{form.elements.project.value=room;const brief='Project studio brief\nMaterial: '+surface+'\nStage: '+$('#readiness').value+'\nDimensions / layout: '+($('#dimensions').value.trim()||'To discuss');const previous=form.elements.message.value;form.elements.message.value=brief+(previous&&!previous.startsWith('Project studio brief')?'\n\n'+previous:'');$('#contact').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#form-note').textContent='Your project choices are included below. Add your contact details, then open your email draft.';});
function inquiry(){const d=new FormData(form);return ['Name: '+d.get('name'),'Email: '+d.get('email'),'Phone: '+(d.get('phone')||'Not provided'),'City: '+d.get('city'),'Project: '+d.get('project'),'Timing: '+d.get('timing'),'','Project details:',d.get('message')].join('\n')}
form.onsubmit=e=>{e.preventDefault();location.href='mailto:arizonagraniteandstone@gmail.com?subject='+encodeURIComponent('Project inquiry: '+form.elements.project.value)+'&body='+encodeURIComponent(inquiry());$('#form-note').textContent='Your email app has been requested. Review and send the draft there. If it does not open, copy your details below or call the team.'};
$('#copy-inquiry').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(inquiry());$('#form-note').textContent='Project details copied. Paste them into an email to arizonagraniteandstone@gmail.com.'}catch{let box=$('#copy-fallback');if(!box){box=document.createElement('textarea');box.id='copy-fallback';box.setAttribute('aria-label','Project details to copy');form.append(box)}box.value=inquiry();box.focus();box.select();$('#form-note').textContent='Select and copy the project details, then paste them into your email.'}});
if('IntersectionObserver'in window)new IntersectionObserver(entries=>{$('.contact-dock').hidden=entries[0].isIntersecting},{threshold:.1}).observe($('#contact'));
})();
