const $=s=>document.querySelector(s);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const touchLayout=matchMedia('(max-width:850px), (pointer:coarse)').matches;
$('.menu').addEventListener('click',()=>{const open=$('nav').classList.toggle('open');$('.menu').setAttribute('aria-expanded',open);$('.menu').textContent=open?'Close':'Menu'});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{$('nav').classList.remove('open');$('.menu').setAttribute('aria-expanded','false');$('.menu').textContent='Menu'}));
const dialog=$('#lightbox');document.querySelectorAll('.project').forEach(b=>b.addEventListener('click',()=>{dialog.querySelector('img').src=`assets/photo-${b.dataset.photo}.jpg`;dialog.querySelector('img').alt=b.querySelector('img').alt;dialog.querySelector('h3').textContent=b.dataset.title;dialog.showModal()}));$('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});$('#year').textContent=new Date().getFullYear();
const materials=[{title:'Everyday life.<br>Elevated.',kicker:'QUIETLY REFINED',copy:'A considered choice for a busy kitchen. Quartz brings a consistent palette and low-maintenance appeal to the heart of your home.',character:'Clean & consistent',use:'Kitchens & vanities'},{title:'One of a kind.<br>By nature.',kicker:'NATURALLY DISTINCTIVE',copy:'Rich mineral patterns give natural granite its individual character. Explore the slab itself to find the movement, tone and detail that speak to you.',character:'Mineral-rich & individual',use:'Countertops & statement surfaces'},{title:'Timeless.<br>Never ordinary.',kicker:'CLASSIC EXPRESSION',copy:'Expressive veining and a luminous surface make marble unmistakable. A beautiful choice to discuss alongside the care needs of your particular space.',character:'Soft depth & flowing veins',use:'Vanities & architectural accents'}];let currentMaterial=0;let update3D=()=>{};
const tabs=[...document.querySelectorAll('[data-material]')];function select(i){currentMaterial=i;const m=materials[i];tabs.forEach((b,n)=>{b.setAttribute('aria-selected',n===i);b.tabIndex=n===i?0:-1});$('#material-panel').setAttribute('aria-labelledby',tabs[i].id);$('#material-title').innerHTML=m.title;$('#material-kicker').textContent=m.kicker;$('#material-copy').textContent=m.copy;$('#character').textContent=m.character;$('#use').textContent=m.use;$('#study-number').textContent='0'+(i+1);update3D(i)}tabs.forEach((b,i)=>{b.addEventListener('click',()=>select(i));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%3;if(e.key==='ArrowLeft')n=(i+2)%3;if(e.key==='Home')n=0;if(e.key==='End')n=2;if(n!==undefined){e.preventDefault();select(n);tabs[n].focus()}})});
if(!reduce&&!touchLayout){let queued=false;addEventListener('scroll',()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{$('.hero-image').style.transform=`translateY(${Math.min(scrollY*.23,230)}px) scale(${1+Math.min(scrollY*.00008,.07)})`;queued=false})},{passive:true})}
async function init3D(){try{const THREE=await import('./assets/three.module.js');const canvas=$('#stone-canvas');const wrap=canvas.parentElement;const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,touchLayout?1.25:2));renderer.setClearColor(0x191b18,0);renderer.shadowMap.enabled=!touchLayout;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(6,4.6,7);camera.lookAt(0,.2,0);scene.add(new THREE.HemisphereLight(0xfff5df,0x484b48,3));const key=new THREE.DirectionalLight(0xffeed4,4);key.position.set(3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;scene.add(key);const rim=new THREE.DirectionalLight(0xc6daef,2);rim.position.set(-5,3,-4);scene.add(rim);
const island=new THREE.Group();island.rotation.y=-.3;scene.add(island);let mat=new THREE.MeshPhysicalMaterial({color:0xffffff,roughness:.24,metalness:.05,clearcoat:.5,clearcoatRoughness:.15});let uniforms={uType:{value:0}};mat.onBeforeCompile=shader=>{shader.uniforms.uType=uniforms.uType;shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vStonePos;').replace('#include <begin_vertex>','#include <begin_vertex>\nvStonePos=position;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>
varying vec3 vStonePos;uniform float uType;
float hash3(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453123);}
float noise3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash3(i),hash3(i+vec3(1,0,0)),f.x),mix(hash3(i+vec3(0,1,0)),hash3(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash3(i+vec3(0,0,1)),hash3(i+vec3(1,0,1)),f.x),mix(hash3(i+vec3(0,1,1)),hash3(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float a=.5,v=0.;for(int i=0;i<5;i++){v+=a*noise3(p);p=p*2.1+vec3(1.3,2.1,.7);a*=.5;}return v;}`);shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
vec3 p=vStonePos;float n=fbm(p*2.2);float vein=abs(sin(p.x*1.7+p.z*2.3+p.y*.8+n*7.));float thin=pow(1.-vein,18.);vec3 base=mix(vec3(.83,.82,.76),vec3(.99,.98,.93),n);vec3 stone=mix(base,vec3(.42,.4,.34),thin*.55);
if(uType>.5&&uType<1.5){float speck=noise3(p*160.);float grain=fbm(p*18.);stone=mix(vec3(.08,.095,.08),vec3(.46,.43,.36),grain);stone+=pow(speck,7.)*.38;}
if(uType>1.5){float v=pow(1.-abs(sin(p.x*2.+p.z*1.7+fbm(p*1.6)*8.)),7.);stone=mix(vec3(.89,.88,.82),vec3(.21,.26,.25),v*.85);stone=mix(stone,vec3(.56,.41,.23),thin*.5);}
diffuseColor.rgb*=stone;`)};
function box(w,h,d,x,y,z,material=mat){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;island.add(mesh);return mesh}
box(4.5,.18,2.05,0,1.05,0);box(.15,1.8,2.05,-2.175,.06,0);box(.15,1.8,2.05,2.175,.06,0);const walnut=new THREE.MeshStandardMaterial({color:0x30251b,roughness:.6});box(3.7,1.65,1.45,0,.05,-.2,walnut);const brass=new THREE.MeshStandardMaterial({color:0xa99469,metalness:.8,roughness:.35});for(let i=-1;i<=1;i++){box(.012,1.25,.012,i*1.2,.04,.532,brass)}
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.28}));ground.rotation.x=-Math.PI/2;ground.position.y=-.85;ground.receiveShadow=true;scene.add(ground);
let targetY=-.3,targetX=0,drag=false,lastX=0,lastY=0,active=true;const observer=new IntersectionObserver(es=>{active=es[0].isIntersecting},{rootMargin:'120px'});observer.observe(wrap);let paintedMaterial=-1;function size(){paintedMaterial=-1;let w=wrap.clientWidth,h=wrap.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(6,4.6,7);if(w/h<1.15)camera.position.multiplyScalar(1.22);camera.updateProjectionMatrix()}new ResizeObserver(size).observe(wrap);size();
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||touchLayout)return;drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;targetY+=(e.clientX-lastX)*.008;targetX=Math.max(-.25,Math.min(.25,targetX+(e.clientY-lastY)*.002));lastX=e.clientX;lastY=e.clientY});['pointerup','pointercancel'].forEach(ev=>canvas.addEventListener(ev,()=>drag=false));$('#rotate-left').addEventListener('click',()=>{targetY-=Math.PI/6});$('#rotate-right').addEventListener('click',()=>{targetY+=Math.PI/6});if(touchLayout)$('.drag-hint').textContent='SWIPE TO SCROLL · TAP TO TURN';$('#reset-view').addEventListener('click',()=>{targetY=-.3;targetX=0});update3D=i=>{uniforms.uType.value=i;mat.roughness=i===1?.38:.24};update3D(currentMaterial);
let last=0;function frame(t){requestAnimationFrame(frame);if(!active||t-last<30)return;last=t;if(touchLayout&&paintedMaterial===currentMaterial&&Math.abs(island.rotation.y-targetY)<.002&&Math.abs(island.rotation.x-targetX)<.002)return;paintedMaterial=currentMaterial;const r=wrap.getBoundingClientRect();let scrollTurn=(reduce||touchLayout)?0:Math.max(-.4,Math.min(.4,(innerHeight*.5-r.top-r.height*.5)/innerHeight))*.5;island.rotation.y+=(targetY+scrollTurn-island.rotation.y)*.07;island.rotation.x+=(targetX-island.rotation.x)*.08;island.position.y=(reduce||touchLayout)?0:Math.sin(t*.0006)*.035;renderer.render(scene,camera)}requestAnimationFrame(frame)
}catch(err){$('#stone-canvas').hidden=true;$('#fallback').hidden=false;$('.drag-hint').textContent='EXPLORE MATERIALS WITH THE TABS';$('#reset-view').hidden=true;$('.touch-rotate').style.display='none';console.warn('3D display unavailable',err)}}init3D();
